import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("privacy", "routes/privacy.tsx"),
  route("vriendenactie", "routes/vriendenactie.tsx"),
  route("r/:code", "routes/r.$code.tsx"),
  route("admin", "routes/admin._index.tsx"),
  route("maatjes/:token", "routes/vrienden.$token.tsx"),
  route("profiel/:token", "routes/profiel.$token.tsx", [
    index("routes/profiel.$token._index.tsx"),
    route("basis", "routes/profiel.$token.basis.tsx"),
    route("naam", "routes/profiel.$token.naam.tsx"),
    route("geslacht", "routes/profiel.$token.geslacht.tsx"),
    route("klassement", "routes/profiel.$token.klassement.tsx"),
    route("kant", "routes/profiel.$token.kant.tsx"),
    route("speelvoorkeur", "routes/profiel.$token.speelvoorkeur.tsx"),
    route("clubs", "routes/profiel.$token.clubs.tsx"),
  ]),
  route("match/nieuw/:token", "routes/match.nieuw.$token.tsx", [
    index("routes/match.nieuw.$token._index.tsx"),
    route("spelers", "routes/match.nieuw.$token.spelers.tsx"),
    route("maatjes", "routes/match.nieuw.$token.vrienden.tsx"),
    route("wanneer", "routes/match.nieuw.$token.wanneer.tsx"),
    route("formaat", "routes/match.nieuw.$token.formaat.tsx"),
    route("uitnodigingen", "routes/match.nieuw.$token.uitnodigingen.tsx"),
    route("bevestigen", "routes/match.nieuw.$token.bevestigen.tsx"),
    route("overzicht", "routes/match.nieuw.$token.overzicht.tsx"),
  ]),
  route("match/deelname/:token", "routes/match.deelname.$token.tsx"),
  route("match/:token/:matchId", "routes/match.$token.$matchId.tsx"),
  route("match/:token", "routes/match.$token.tsx"),
  route("i/:token", "routes/i.$token.tsx"),
  route("i/:token/nee", "routes/i.$token.nee.tsx"),
  route("dev/simulator", "routes/dev.simulator.tsx"),
  route("dev/cron-tick", "routes/dev.cron-tick.tsx"),
  route("api/padelstats/members/search", "routes/api.padelstats.members.search.ts"),
  route("api/cron/cascade-tick", "routes/api.cron.cascade-tick.tsx"),
  route("api/cron/send-tick", "routes/api.cron.send-tick.tsx"),
  route("webhooks/twilio/whatsapp", "routes/webhooks.twilio.whatsapp.ts"),
] satisfies RouteConfig;
